alps/urls.py
from django.contrib import admin
from django.urls import path
from alps import views

app_name ='alps'

admin.site.site_title = "ILOVEALPS Admin Portal"
admin.site.site_header = "ILOVEALPS Administration"
admin.site.index_title = "Welcome to ILOVEALPS Portal"


urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('sports/', views.sports, name='sports'),
    path('contatti/', views.contatti, name='contatti'),
    path('luoghi/', views.luoghi, name='places'),
    path('alps/<int:activity_id>', views.details, name='details'),



]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alps.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alps/models.py
from __future__ import unicode_literals
from django.db import models


# Create your models here.
class Activity(models.Model):
    CHOICES = (
        ('sport', 'Sport'),
        ('luoghi', "Luoghi d'interesse"),
        ('piatti', 'Piatti tipici'),
        ('after ski', 'After Ski'),
        ('cena', 'Cena in quota'),
    )

    category = models.CharField(max_length=150, null=False, choices=CHOICES)
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=350)
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title


class Contact(models.Model):
    nameAdministrator = models.CharField(max_length=150)
    streetNumber = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    phone = models.CharField(max_length=150)
    partitaIva = models.CharField(max_length=150)
    email = models.CharField(max_length=150)

    emailBluchalet = models.CharField(max_length=150)
    phoneBluchalet = models.CharField(max_length=150)
    homepageBluchalet = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.nameAdministrator

alps/views.py
from django.shortcuts import render, get_object_or_404
from .models import Activity, Contact

# Create your views here.


def home(request):
    contactall = get_object_or_404(Contact, pk=1)
    activities = Activity.objects.all()
    sport_activities = Activity.objects.filter(category='sport')[:4]
    enos = Activity.objects.filter(category='after ski')[:2]
    places = Activity.objects.filter(category='luoghi')[:2]

    return render(request, 'alps/home.html', {'contactall': contactall, 'activities': activities,
                                              'sport_activities': sport_activities,
                                              'enos': enos, 'places': places})


def base(request):
    contactallbase = get_object_or_404(Contact, pk=1)
    return render(request, 'alps/base.html', {'contactallbase': contactallbase})


def contatti(request):
    return render(request, 'alps/contatti.html',)


def sports(request):
    contactall = get_object_or_404(Contact, pk=1)
    sport_activities = Activity.objects.filter(category='sport')
    # sport_activities = Activity.objects.get(category='sport')   -- GET only for one object
    enos = Activity.objects.filter(category='after ski')[:2]
    places = Activity.objects.filter(category='luoghi')[:2]
    return render(request, 'alps/sports.html', {'contactall': contactall, 'sport_activities': sport_activities,
                                                'enos': enos, 'places': places})


def luoghi(request):
    contactall = get_object_or_404(Contact, pk=1)
    sport_activities = Activity.objects.filter(category='sport')[:2]
    enos = Activity.objects.filter(category='after ski')[:2]
    places = Activity.objects.filter(category='luoghi')
    return render(request, 'alps/luoghi.html', {'contactall': contactall, 'sport_activities': sport_activities,
                                                'enos': enos, 'places': places})


def details(request, activity_id):
    contactall = get_object_or_404(Contact, pk=1)
    activities = Activity.objects.all()
    activity = get_object_or_404(Activity, pk=activity_id)
    return render(request, 'alps/details.html', {'contactall': contactall, 'activity': activity})

alps/templates/alps/base.html
{% load static %}

<!doctype html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    <title>Vacanze in Valle d'Aosta | una guida alle attività da svolgere in montagna</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'alps/cropped-Logo-alps3-32x32.png' %}"/>
</head>
<body>


<nav  class="navbar sticky-top navbar-expand-lg navbar-light bg-light ">
        <a href="{% url 'alps:home' %}">
        <img src="{% static 'alps/logoc.png' %}" width="250 " height="90"  class="d-inline-block align-top">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse flex-row-reverse" id="navbarNavDropdown">
            <ul class="navbar-nav ">
                <div class="container">
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'alps:home' %}">I love Alps</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'alps:sports' %}">Sport</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Enogastronomia
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Piatti tipici</a>
                            <a class="dropdown-item" href="#">After ski</a>
                            <a class="dropdown-item" href="#">Cena in quota</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'alps:places' %}">Luoghi d'interesse</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.bluchalet.it/categoria_immobili/monti/" target="_blank">I nostri appartamenti</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"  href="{% url 'alps:contatti' %}">Contatti</a>
                    </li>
                </div>
            </ul>
        </div>
</nav>


{% block content %}


{% endblock %}


<br/>
<br/>
<!--
<div class="container">
    {{ contactallbase.city }}
    {{ contactall.streetNumber }}
    {{ contactall.phone }}
    {{ contactall.partitaIva }}
    {{ contactall.email }}
    {{ contactall.nameAdministrator }}
</div>
{{ contactall.city }}
-->



<footer>
    <div class="container-fluid footer text-center">

        <img src="{% static 'alps/logo.png' %} ">
        <br/>
        <br/>
        <a> Via Rimassa 37/13, Genova </a>|<a> +39 3483799393 </a>|<a> P.iva 02568240994 </a>|<a> info@ilovealps.it</a>
        <br/>
        <br/>
        <a>©All rights reserved. Privacy Policy </a>|<a> Cookie Policy</a>
    </div>
</footer>

<!--div class="container text-center">

    <img src="{% static 'alps/logo.png' %} ">
    <br/>
    <br/>
    <a> Via Rimassa 37/13, Genova </a>|<a> +39 3483799393 </a>|<a> P.iva 02568240994 </a>|<a> info@ilovealps.it</a>
    <br/>
    <br/>
    <a>©All rights reserved. Privacy Policy </a>|<a> Cookie Policy</a>

</div-->


</body>
</html>

alps/templates/alps/contatti.html
{% extends 'alps/base.html' %}
{% load static %}
{% block content %}

<br/>


<h3 class="mt-5 text-center" style="font-size: 40px">I nostri contatti</h3>
<h5 class="mt-1 text-center" style="font-size: 22px; color:#d98d76">Scrivici per maggiori informazioni!</h5>

<br/>
<br/>

<div class=" container">

        <div class="form-group">
            <label for="usr">Nome e Cognome:</label>
            <input type="text" class="form-control" id="usr">
        </div>
        <div class="form-group">
            <label for="pwd">Email</label>
            <input type="password" class="form-control" id="pwd">
        </div>
    <div class="form-group">
        <label for="usr">Oggeto</label>
        <input type="text" class="form-control" id="usr">
    </div>
    <div class="form-group">
        <label for="pwd">Messagio</label>
        <input type="password" class="form-control" id="pwd">
    </div>


        <br/>
            <br/>
            <br/>


</div>











<br/>
<br/>
<br/>
<br/>

{% endblock %}

alps/templates/alps/details.html
{% extends 'alps/base.html' %}
{% load static %}
{% block content %}

<style>
ul {
display: block;
list-style-type: circle;
margin-top: 1em;
margin-bottom: 1 em;
margin-left: 0;
margin-right: 0;
padding-left: 30px;
}
</style>
<br/>
<br/>
<div class="container">
    <div class="row">
        <div class="col-lg-8 mt-4 text-center">

            <h1 style="mt-4; font-size: 40px; margin: 0px; text-align: left;">{{ activity.title }}</h1>

            <img src="{{ activity.image.url }}" class="img-fluid mt-4"  height="600">
            <br/>
            <h2 class="mt-4" style="font-size: 20px; margin: 0px; text-align: left; color:#d98d76">{{ activity.description }}</h2><br/>
            <p style="font-size: 16px; line-height: 24px; text-align: left;">
                {{ activity.text|linebreaks }}</p>
            <a style="mt-4; font-size: 16px; line-height: 24px; text-align: left" class="nav-link " href="{{ activity.url }}" target="_blank">{{ activity.url }}</a>
        </div>
        <div class="col-8 col-sm-4">
            <div class="container-sm">
                <!-- Content here -->
                <br/>
                <br/>
                <h6 style="font-size: 20px; margin: 0px; text-align: left;">Cerca</h6>
                <br/>
                <br/>
                <br/>
                <h6 style="font-size: 20px; margin: 0px; text-align: left;">Categorie</h6>
                <ul>
                    <li>After ski</li>
                    <li>Attivita sportive</li>
                    <li>Castelli & Forti</li>
                    <li>Cena in quota</li>
                    <li>Enogastronomia</li>
                    <li>In evidenza</li>
                    <li>Luoghi d'interesse</li>
                    <li>Piatti tipici</li>
                    <li>Spa&Wellness</li>
                    <li>Sport in primo piano</li>
                </ul>

            </div>
        </div>
    </div>
</div>












<br/>
<br/>
<br/>
<br/>

{% endblock %}

alps/templates/alps/home.html
{% extends 'alps/base.html' %}
{% load static %}
{% block content %}

<!--Berg bild   wechsekn mit   / SLIDER  -->

<div id="carouselExampleFade" class="carousel slide carousel-fade" data-interval="5000" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="static/alps/mountaineering.jpg" alt="Mountaineering">
            <div class="container" >

                <div class="carousel-caption">
                    <h1 style="font-size: 55px">ATTIVITÁ</h1><h1 style="font-size: 55px; color:#d98d76"> SPORTIVE</h1>
                    <p style="font-size: 22px">Ognuno di noi ha una passione differente, c’è chi ama sciare nella polvere fresca,
                        c’è chi ama andare in Mountain Bike e scendere a tutta birra. </p>
                </div>

            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="static/alps/matterhorn.jpg" alt="Matterhorn">
            <div class="carousel-caption ">
                <h1 style="font-size: 55px">VACANZE IN</h1><h1 style="font-size: 55px; color:#d98d76">  VALLE D'AOSTA</h1>
                <p style="font-size: 22px">Una guida variegata sulle varie attività da svolgere in Valle d’Aosta.
                    Un modo per promuovere le località dove lavoriamo.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="static/alps/manning.jpg" alt="Manning">
            <div class="carousel-caption ">
                <h1 style="font-size: 55px">VACANZE IN</h1><h1 style="font-size: 55px; color:#d98d76"> RELAX</h1>
                <p style="font-size: 22px">Per una vacanza dedicata alla buona cucina o alla scoperta di luoghi incantati delle nostre valli.
                    Terme, centri benessere, castelli e tanto altro. </p>
            </div>
        </div>
    </div>

    <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>



<body>

<br/>
<br/>
<br/>
<br/>
<!--
{{ contactall.city }}
{{ contactall.streetNumber }}
{{ contactall.phone }}
{{ contactall.partitaIva }}
{{ contactall.email }}
{{ contactall.nameAdministrator }}
-->

<div class="container">
    <div class="row">
        <div class="col-md-8 ">
            <img src="static/alps/home_alm.jpg " class="img-fluid"  height="600">
        </div>
        <div class="col-6 col-md-4">
            <div class="container-sm">
                <!-- Content here -->
                <h1 style="font-size: 40px; margin: 0px; text-align: left;">Siamo un gruppo di Property Managers.</h1>
                <br/>
                <h2 style="font-size: 20px; margin: 0px; text-align: left; color:#d98d76">Gestiamo da diversi anni case vacanza in
                Piemonte e Valle d’Aosta e condividiamo la passione per i posti in cui lavoriamo ancor prima del
                lavoro stesso</h2><br/>
                <p style="font-size: 16px; line-height: 24px; text-align: left;">
                    Ognuno di noi ha una passione differente, c’è chi ama sciare nella polvere fresca,
                    c’è chi ama andare in Mountain Bike e scendere a tutta birra, chi ama arrampicare su
                    ipide falesie oppure semplicemente fare trekking o pescare trote ad alta quota.</p>
                <p style="font-size: 16px; line-height: 24px; text-align: left;">Al di là delle varie
                    attività sportive praticate, abbiamo tutti una passione in comune: siamo di buona
                    forchetta (e bicchiere!).</p>
                <p style="font-size: 16px; line-height: 24px; text-align: left;">Quindi abbiamo deciso
                    di contribuire con la nostra esperienza a creare un Blog che avesse la funzione di
                    offrire una guida sulle varie attività da svolgere nei posti in cui abbiamo le
                    nostre strutture e al tempo stesso promuovere le località in cui lavoriamo.
                <p>ISCRIVITI ALLA NEWSLETTER:
                    Riceverai mensilmente le nostre offerte delle strutture che gestiamo.</p>
            </div>
        </div>
    </div>
</div>
<hr>



<h2 class="mt-5 text-center" >LE ALPI IN EVIDENZA</h2>
<hr>
<div class=" container">
    <div class="row" >
        {% for activity in activities %}
        <div class="col-lg-4 col-md-6" >

            <img src="{{ activity.image.url }}" class="img-fluid" width="400">

            <h3>{{ activity.title }}</h3>
            <p>{{ activity.description }}</p>
            <!--BUTTON color=#d98d76-->
            <a href="{% url 'alps:details' activity.id %}" class="btn btn-secondary btn-sm active"
               role="button" aria-pressed="true">Leggi tutto</a>
            <br/>
            <br/>
            <br/>
        </div>
        {% endfor %}
    </div>
</div>

<br/>
<br/>
<br/>
<h2 class="mt-5 text-center" >ATTIVITÁ SPORTIVE</h2>
<hr>
<div class=" container">
    <div class="row ">

                {% for sport_activity in sport_activities %}
                <div class="col-lg-3 col-md-5">
                    <!--                <div class="card" style="width: 18rem; ">
                                        <img src="{{ sport_activity.image.url }}" class="card-img-top" alt="...">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ sport_activity.title }}</h5>
                                            <p class="card-text">{{ sport_activity.description }}</p>
                                            <a href="#" class="btn btn-primary">Go somewhere</a>
                                        </div>  -->


                    <img src="{{ sport_activity.image.url }}" class="img-fluid" width="400">

                    <h3>{{ sport_activity.title }}</h3>
                    <p>{{ sport_activity.description }}</p>
                    <a href="{% url 'alps:details' sport_activity.id %}" class="btn btn-secondary btn-sm active"
                       role="button" aria-pressed="true">Leggi tutto</a>


                </div>
                {% endfor %}

    </div>
</div>
<hr>

</body>


{% endblock %}

alps/templates/alps/luoghi.html
{% extends 'alps/base.html' %}
{% load static %}
{% block content %}

<br/>




<h3 class="mt-5 text-center" style="font-size: 40px">Luoghi d’interesse</h3>
<h5 class="mt-4 text-center" style="font-size: 22px; color:#d98d76">Scopri con noi come trascorre il tempo libero durante la tua vacanza in Valle d’Aosta
                                            tra </h5>
<h5 class=" text-center" style="font-size: 22px; color:#d98d76"> SPA&WELLNESS e visite guidate in luoghi magici ed incantati. </h5>
<p class="mt-3 text-center" style="font-size: 18px">La Valle d’Aosta non è solo sport e cibo. In questa sessione trovi una selezione
                                    di attività non sportive da praticare durante la tua vacanza in Valle d’Aosta. </p>
<br/>
<br/>


<div class=" container">
    <div class="row ">
        {% for place in places %}
        <div class="col-lg-4 col-md-6" >
            <div class="shadow-box-example z-depth-1 flex-center">

                    <img src="{{ place.image.url }}" class="img-fluid" width="400">
                    <h3>{{ place.title }}</h3>
                    <p>{{ place.description }}</p>
                    <a href="{% url 'alps:details' place.id %}" class="btn btn-secondary btn-sm active"
                        role="button" aria-pressed="true">Leggi tutto</a>
                    <br/>
                    <br/>
                    <br/>

            </div>
        </div>
        {% endfor %}
    </div>
</div>

<br/>
<br/>

<div class="container">
    <div class="row">
        <div class="col ">
            <div class="container-sm" >
                <h2 style="font-size: 20px; margin: 0px; text-align: center;" class="mt-5 text-center" >ATTIVITÁ SPORTIVE</h2>
                <hr>
                <div class=" container">
                    <div class="row ">
                        {% for sport_activity in sport_activities %}
                        <div class="col-md-6">
                            <img src="{{ sport_activity.image.url }}" class="img-fluid" width="400">
                            <h3>{{ sport_activity.title }}</h3>
                            <p>{{ sport_activity.description }}</p>
                            <a href="{% url 'alps:details' sport_activity.id %}" class="btn btn-secondary btn-sm active"
                               role="button" aria-pressed="true">Leggi tutto</a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="container-sm">
                <h2 style="font-size: 20px; margin: 0px; text-align: center;" class="mt-5 text-center">ENOGASTRONOMIA</h2>
                <hr>
                <div class=" container">
                    <div class="row ">
                        {% for eno in enos %}
                        <div class="col-md-6">
                            <img src="{{ eno.image.url }}" class="img-fluid" width="400">
                            <h3>{{ eno.title }}</h3>
                            <p>{{ eno.description }}</p>
                            <a href="{% url 'alps:details' eno.id %}" class="btn btn-secondary btn-sm active"
                               role="button" aria-pressed="true">Leggi tutto</a>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<br/>
<br/>
<br/>
<br/>

{% endblock %}

alps/templates/alps/sports.html
{% extends 'alps/base.html' %}
{% load static %}
{% block content %}

<br/>


<!--{{ sport_activities }}-->


<h3 class="mt-5 text-center" style="font-size: 40px">Attività sportive</h3>
<h5 class="mt-5 text-center" style="font-size: 22px; color:#d98d76">Dai sfogo alla tua adrenalina, prenota con noi la tua esperienza! </h5>
<p class="mt-5 text-center" style="font-size: 18px">In questa sessione troverai una selezione di attività adrenaliniche selezionate per
    voi dai nostri Property Managers più coraggiosi da praticare in tutta la Valle d’Aosta. </p>
<br/>
<br/>


<div class=" container">
    <div class="row ">
        {% for sport_activity in sport_activities %}
        <div class="col-lg-4 col-md-6" >
            <div class="shadow-box-example z-depth-1 flex-center">

                    <img src="{{ sport_activity.image.url }}" class="img-fluid" width="400">
                    <h3>{{ sport_activity.title }}</h3>
                    <p>{{ sport_activity.description }}</p>
                    <a href="{% url 'alps:details' sport_activity.id %}" class="btn btn-secondary btn-sm active"
                    role="button" aria-pressed="true">Leggi tutto</a>
                    <br/>
                    <br/>
                    <br/>

            </div>
        </div>
        {% endfor %}
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col ">
            <div class="container-sm" >
                <h2 style="font-size: 20px; margin: 0px; text-align: center;" class="mt-5 text-center" >ENOGASTRONOMIA</h2>
                <hr>
                <div class=" container">
                    <div class="row ">
                        {% for eno in enos %}
                        <div class="col-md-6">
                            <img src="{{ eno.image.url }}" class="img-fluid" width="400">
                            <h3>{{ eno.title }}</h3>
                            <p>{{ eno.description }}</p>
                            <a href="{% url 'alps:details' eno.id %}" class="btn btn-secondary btn-sm active"
                               role="button" aria-pressed="true">Leggi tutto</a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="container-sm">
                <h2 style="font-size: 20px; margin: 0px; text-align: center;" class="mt-5 text-center">LUOGHI D'INTERESSE</h2>
                <hr>
                <div class=" container">
                    <div class="row ">
                        {% for place in places %}
                        <div class="col-md-6">
                            <img src="{{ place.image.url }}" class="img-fluid" width="400">
                            <h3>{{ place.title }}</h3>
                            <p>{{ place.description }}</p>
                            <a href="{% url 'alps:details' place.id %}" class="btn btn-secondary btn-sm active"
                               role="button" aria-pressed="true">Leggi tutto</a>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<br/>
<br/>
<br/>
<br/>

{% endblock %}